# Generated by Django 4.2.4 on 2023-09-06 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Point de vente')),
                ('address', models.CharField(max_length=100, verbose_name='Adresse')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='BP')),
                ('city', models.CharField(max_length=50, verbose_name='Ville')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Pays')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salespoints', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(blank=True, default='lambda', max_length=150, null=True, verbose_name='Nom du client')),
                ('qty', models.IntegerField(default=0)),
                ('total', models.FloatField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='records.product', verbose_name='Produit')),
                ('sales_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales.salespoint', verbose_name='Point de vente')),
            ],
        ),
    ]
